language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
env:
  - CI=false
#install AWS CLI tools
before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
script:
  - npm run build
deploy:
  provider: script
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  script: ~/.local/bin/aws s3 sync build s3://socrates-fhir-ignite.com --region=us-east-1 --delete
  skip_cleanup: true
  on:
    branch: master


# env:
#   - CI=false
# language: node_js
# node_js:
#   - 8
# cache:
#   directories:
#     - node_modules

# #install AWS CLI tools
# install: pip install awscli
# script:
#   - npm run build
# deploy:
#   provider: script
#   script: ~/.local/bin/aws s3 sync dist s3://socrates-fhir-ignite.com --region=us-east-1 --delete
#   access_key_id: "AKIAJ7WP7PPNCTUF7LNQ"
#   secret_access_key: "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"
#   skip_cleanup: true