language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm run build
deploy:
  provider: script
  script: ~/.local/bin/aws s3 sync dist s3://socrates-fhir-ignite.com --region=us-east-1 --delete
  access_key_id: "AKIAJ7WP7PPNCTUF7LNQ"
  secret_access_key: "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"
  skip_cleanup: true
  local_dir: build
  on:
    branch: master